apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tictac
  namespace: nokia
  labels:
    io.kompose.service: tictac
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: tictac
    spec:
      containers:
      - image: nokia/tictac:v1
        name: web
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
      restartPolicy: Always